### ISSUE TITLE
방만들기 페이지 캐릭터 연동

### ISSUE THREAD

**Issue by JisuuungKim** [KMU-WINK/nogari#61]
# 설명

/choose_char에서 캐릭터 생성을 완료했을경우 만든 캐릭터의 종류(이미지)와 이름을 /find 에서 보여줄 것

# 참고사항
현재모습
![image](https://user-images.githubusercontent.com/66466139/132100291-ee6185fb-eabe-4ccc-b0df-a4b70a9ef793.png)

개선 후 모습
![image](https://user-images.githubusercontent.com/66466139/132100350-d9878538-b8d1-4088-bcea-84521347c4a2.png)

# out of scope
-캐릭터 연동 외에 다른 요소는 수정하지 않아도 된다

**Comment by bell2lee** [comment]
dependency by #60 #62 

@JisuuungKim 마지 해주세요
